
services:
  # 1. Base de Datos
  postgres:
    image: postgres:15-alpine
    container_name: taller_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: taller_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Almacenamiento de Imágenes (S3 Compatible)
  minio:
    image: minio/minio
    container_name: taller_minio
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console Port (Web UI)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # 3. Interfaz visual para Postgres (Opcional pero útil)
  pgadmin:
    image: dpage/pgadmin4
    container_name: taller_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data:
  minio_data: